import React, { useRef, useState } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet,
  SafeAreaView, ScrollView, Platform,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Feather } from '@expo/vector-icons';
import { log } from '../utils/logger';

const TERMS = [
  {
    heading: '1. Nature of the App',
    body: 'ADChronotype is a statistical research and awareness tool. It is designed to help users understand the relationship between their sleep chronotype, lifestyle factors, and Alzheimer\'s disease risk factors. It is NOT a medical device, clinical diagnostic tool, or treatment platform of any kind.',
  },
  {
    heading: '2. Not a Clinical Diagnosis',
    body: 'The scores, predictions, and assessments generated by ADChronotype are statistical comparisons to research data. They do NOT predict whether you will develop Alzheimer\'s Disease or any other medical condition. Your score reflects similarity to research datasets — nothing more. Do not make any medical decisions based on the output of this app.',
  },
  {
    heading: '3. Consult a Professional',
    body: 'If you have concerns about your cognitive health, memory, or any symptoms that worry you, please consult a licensed medical professional immediately. ADChronotype is not a substitute for professional medical advice, diagnosis, or treatment.',
  },
  {
    heading: '4. Data Collection & Use',
    body: 'By using ADChronotype, you acknowledge that the owners of the app will have access to all lifestyle factors you enter (sleep type, sleep times, age, BMI, ethnicity, family history) as well as your generated score and its factor breakdown. This data is used solely for research purposes and improving the app.',
  },
  {
    heading: '5. Data Security',
    body: 'Your account is confidential to the extent that your password is encrypted using bcrypt hashing (SHA-256 equivalent). However, your lifestyle data and scores are accessible to the app owners as described above. We do not sell your data to third parties.',
  },
  {
    heading: '6. No Warranty',
    body: 'ADChronotype is provided "as is" without any warranty of any kind, express or implied. The app owners make no representations or warranties regarding the accuracy, completeness, or suitability of the information provided.',
  },
  {
    heading: '7. Limitation of Liability',
    body: 'To the fullest extent permitted by law, the owners of ADChronotype shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of this app or reliance on any information it provides.',
  },
  {
    heading: '8. Changes to Terms',
    body: 'We reserve the right to update these Terms and Conditions at any time. Continued use of the app after any changes constitutes acceptance of the new terms. We will notify users of significant changes through the app.',
  },
  {
    heading: '9. Age Requirement',
    body: 'ADChronotype is intended for users aged 18 and above. By using this app you confirm that you are at least 18 years of age.',
  },
  {
    heading: '10. Acceptance',
    body: 'By tapping "I Accept" below, you confirm that you have read, understood, and agree to all of the above Terms and Conditions and acknowledge that ADChronotype is not a medical diagnostic tool.',
  },
];

export default function TermsScreen({ navigation, route }) {
  const [reachedBottom, setReachedBottom] = useState(false);
  const scrollRef = useRef(null);

  function handleScroll({ nativeEvent }) {
    const { contentOffset, contentSize, layoutMeasurement } = nativeEvent;
    const distFromBottom = contentSize.height - contentOffset.y - layoutMeasurement.height;
    if (distFromBottom < 40) setReachedBottom(true);
  }

  function handleAccept() {
    log.info('TermsScreen: user accepted T&C');
    // Pass accepted=true back to SplashScreen via navigation param
    navigation.navigate('Splash', { accepted: true });
  }

  return (
    <>
      <SafeAreaView style={styles.safeTop} />
      <SafeAreaView style={styles.safeBottom}>
        <View style={styles.root}>
          <LinearGradient colors={['#05082a', '#0a0d3a']} style={StyleSheet.absoluteFillObject} />

          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
              <Feather name="chevron-left" size={24} color="#fff" />
            </TouchableOpacity>
            <Text style={styles.headerTitle}>Terms & Conditions</Text>
            <View style={{ width: 32 }} />
          </View>

          {!reachedBottom && (
            <View style={styles.scrollHint}>
              <Text style={styles.scrollHintText}>↓ Scroll to the bottom to accept</Text>
            </View>
          )}

          <ScrollView
            ref={scrollRef}
            style={styles.scroll}
            contentContainerStyle={styles.scrollContent}
            onScroll={handleScroll}
            scrollEventThrottle={100}
            showsVerticalScrollIndicator={true}
          >
            <Text style={styles.lastUpdated}>Last updated: July 2026</Text>

            <View style={styles.disclaimerBox}>
              <Text style={styles.disclaimerText}>
                ⚠️  ADChronotype is a <Text style={styles.bold}>statistical research tool only</Text> — not a medical diagnostic tool.
              </Text>
            </View>

            {TERMS.map((section, i) => (
              <View key={i} style={styles.section}>
                <Text style={styles.sectionHeading}>{section.heading}</Text>
                <Text style={styles.sectionBody}>{section.body}</Text>
              </View>
            ))}

            <View style={{ height: 30 }} />
          </ScrollView>

          {/* Accept button — only active after scrolling to bottom */}
          <View style={styles.footer}>
            {!reachedBottom && (
              <Text style={styles.footerHint}>Please read all terms before accepting</Text>
            )}
            <TouchableOpacity
              style={[styles.acceptBtn, !reachedBottom && styles.acceptBtnDisabled]}
              onPress={handleAccept}
              disabled={!reachedBottom}
              activeOpacity={0.85}
            >
              <Text style={styles.acceptBtnText}>
                {reachedBottom ? 'I Accept — Get Started →' : 'Scroll to the bottom to accept'}
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </SafeAreaView>
    </>
  );
}

const styles = StyleSheet.create({
  safeTop:    { flex: 0, backgroundColor: '#05082a', paddingTop: Platform.OS === 'android' ? 25 : 0 },
  safeBottom: { flex: 1, backgroundColor: '#05082a' },
  root:       { flex: 1 },

  header:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#1a1a40' },
  backBtn:     { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },

  scrollHint:     { backgroundColor: '#7c3aed22', paddingVertical: 7, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#7c3aed33' },
  scrollHintText: { color: '#7c3aed', fontSize: 11, fontWeight: '600' },

  scroll:        { flex: 1 },
  scrollContent: { padding: 20 },
  lastUpdated:   { color: '#4a5270', fontSize: 11, marginBottom: 16 },

  disclaimerBox:  { backgroundColor: 'rgba(10,8,40,0.9)', borderRadius: 12, padding: 14, marginBottom: 20, borderWidth: 1.5, borderColor: '#ffb83066' },
  disclaimerText: { color: '#c0c0d0', fontSize: 13, lineHeight: 20 },
  bold:           { color: '#ffb830', fontWeight: '800' },

  section:         { marginBottom: 22 },
  sectionHeading:  { color: '#ffffff', fontSize: 14, fontWeight: '700', marginBottom: 8 },
  sectionBody:     { color: '#8c91b5', fontSize: 13, lineHeight: 21 },

  footer:           { padding: 16, borderTopWidth: 1, borderTopColor: '#1a1a40', backgroundColor: '#05082a' },
  footerHint:       { color: '#4a5270', fontSize: 11, textAlign: 'center', marginBottom: 8 },
  acceptBtn:        { backgroundColor: '#7c3aed', borderRadius: 14, height: 52, alignItems: 'center', justifyContent: 'center' },
  acceptBtnDisabled:{ backgroundColor: '#2a1a60', opacity: 0.6 },
  acceptBtnText:    { color: '#fff', fontSize: 15, fontWeight: '700' },
});
