export const RESEARCH_DISCLAIMER =
  'This is not an official diagnosis or a clinical risk assessment. This score is generated by ADChronotype’s independently trained machine-learning model using the information you provide. It is a statistical research estimate and does not predict whether you will develop Alzheimer’s disease or another medical condition. Do not use this score to make medical decisions. Discuss health concerns with a qualified healthcare professional.';

export const RESEARCH_DISCLAIMER_SHORT =
  'This research score is not a diagnosis and should not be used for medical decisions.';

export const RESEARCH_METHODOLOGY =
  'The model evaluates age, BMI, ethnicity, chronotype, sleep timing, and sleep duration. Published research has reported associations between these factors and Alzheimer’s disease or cognitive-health risk. Association does not establish causation.';

export const RESEARCH_SOURCES = [
  { label: 'Age', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3475404/' },
  { label: 'BMI', url: 'https://pubmed.ncbi.nlm.nih.gov/33880516/' },
  { label: 'Ethnicity', url: 'https://pubmed.ncbi.nlm.nih.gov/34882963/' },
  { label: 'Chronotype', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12434255/' },
  { label: 'Sleep timing', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11071685/' },
];

export const researchSourcesText = () => [
  'Research Sources',
  ...RESEARCH_SOURCES.map(source => `${source.label}: ${source.url}`),
].join('\n');
